use_frameworks!

platform :ios, '11.0'

target 'RCSceneNetworkKit_Example' do
  pod 'RCSceneNetworkKit', :path => '../'

  target 'RCSceneNetworkKit_Tests' do
    inherit! :search_paths

    
  end
end
